version: '3.8'

services:
  app:
    image: project-service-app
    container_name: project-service-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: unless-stopped


  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
